### ISSUE TITLE
Would adding 403 to the wiki_check.py r.status_code fallback to get break something?

### ISSUE THREAD

**Issue by ThatLurker** [saveweb/wikiteam3#13]
Some websites fail with:
Resp: POST 403 Forbidden https://wiki.rage.mp/index.php?title=Main_Page
ERROR: Unsupported wiki. Wiki engines supported are: MediaWiki

So checking with get instead of post might be a fix for that, but would just adding 403 there break something elsewhere?

    if r.status_code == 405 or r.status_code == 403 or r.text == "":
        r = session.get(url=url, timeout=120)
    result = r.text

https://github.com/saveweb/wikiteam3/blob/892ea09dc628a705d19ae3281fee1fbd2d2f57b3/wikiteam3/dumpgenerator/api/wiki_check.py#L15C1-L17C20

**Comment by yzqzss** [comment]
> https://wiki.rage.mp/index.php?title=Main_Page

This wiki uses CloudFlare,it pops up cloudflare captcha for me.

> but would just adding 403 there break something elsewhere?

Are you sure everything will work properly after adding 403 to use GET here?

**Comment by ThatLurker** [comment]
In the EU on my home server I do not get a captcha with  GET in curl.
On my Hetzner servers I do get a captcha.
So thats why I wanted to know if something would still detect the captcha if you would do a GET request on error 403.
