### ISSUE TITLE
Incremental dump

### ISSUE THREAD

**Issue by Superraptor** [saveweb/wikiteam3#23]
I posted this somewhat here (https://github.com/orgs/mediawiki-client-tools/discussions/251), but figured this might also be a good place to ask.

Is it currently possible to have the wikiteam3 dump generator update a previous dump instead of generating a new dump from scratch? It would save a lot of time versus brand new dumps every single time. I'm thinking that if it knows the latest timepoint it has created from, it could pull all updates since that timepoint?

Is this a possibility?

Thanks so much!

**Comment by yzqzss** [comment]
#24

**Comment by yzqzss** [comment]
> #24


Waiting for your feedback :eyes:

**Comment by Superraptor** [comment]
This works! Thanks so much!
