### ISSUE TITLE
Bypass Internet Archive item check

### ISSUE THREAD

**Issue by Anonymous-BCFED** [saveweb/wikiteam3#32]
This tool is using the Internet Archive scraper API to talk to MediaWiki.  As of time of writing, the [Internet Archive is being DDoSed](https://www.theverge.com/2024/10/9/24266419/internet-archive-ddos-attack-pop-up-message), leaving wikiteam3 unable to function.

I'd like to request the option to use an alternative until the current drama has ended.

This may seem like a nonsense request, since most people appear to use this tool to upload to IA, but my use-case is to back up public wikis on wikifarms like Miraheze in case they get deleted for one reason or another.

**Comment by yzqzss** [comment]
Hi, please use the option `--force` to skip the IA item check.

**Comment by Anonymous-BCFED** [comment]
Thanks.

**Comment by DigitalDwagon** [comment]
With the Internet Archive back online, I think this is safe to close.
