### ISSUE TITLE
Crashing on windows due to paths

### ISSUE THREAD

**Issue by alexlambson** [saveweb/wikiteam3#38]
Loading `config.json` and `{wikiname}-current.xml` `-title.txt` etc all fail on windows due to string formating a `/` symbol. I'll PR  a fix

**Comment by yzqzss** [comment]
Although I don't have a Windows environment.
IIRC, Python automatically converts the forward slashes to backslashes before interacting with the file system on Windows.

**Comment by alexlambson** [comment]
It was hard crashing any time I tried to resume. The issue may have been that the slashes were mixed. My input was similar to `C:\\folder1\\folder2/config.json`. I was able to get around it by editing the code to use pathlib. If you're open to a PR then I can make the change to use pathlib. 

While we're chatting, I just want to say thank you for the tool. It's amazing!

**Comment by alexlambson** [comment]
Actually, I am going to close the issue. I can't reproduce it now. I don't know what was going on and causing the crash. My apologies
